# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeKAMA <- function(alpha, alphaComplement, KAMA, price) {
    .Call('_FinMarkets_computeKAMA', PACKAGE = 'FinMarkets', alpha, alphaComplement, KAMA, price)
}

computeFRAMA <- function(alpha, alphaComplement, FRAMA, price) {
    .Call('_FinMarkets_computeFRAMA', PACKAGE = 'FinMarkets', alpha, alphaComplement, FRAMA, price)
}

computeItrend <- function(price, iTrend, alpha) {
    .Call('_FinMarkets_computeItrend', PACKAGE = 'FinMarkets', price, iTrend, alpha)
}

computeVIDA <- function(k, price, filt, consts) {
    .Call('_FinMarkets_computeVIDA', PACKAGE = 'FinMarkets', k, price, filt, consts)
}

Ver <- function(x) {
    .Call('_FinMarkets_Ver', PACKAGE = 'FinMarkets', x)
}

